// Mocks generated by Mockito 5.4.6 from annotations
// in soteria/test/features/wallet/wallet_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:soteria/features/wallet/domain/models/wallet.dart' as _i2;
import 'package:soteria/features/wallet/domain/models/wallet_transaction.dart'
    as _i3;
import 'package:soteria/features/wallet/domain/models/wallet_transaction_type.dart'
    as _i6;
import 'package:soteria/features/wallet/domain/repositories/wallet_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWallet_0 extends _i1.SmartFake implements _i2.Wallet {
  _FakeWallet_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWalletTransaction_1 extends _i1.SmartFake
    implements _i3.WalletTransaction {
  _FakeWalletTransaction_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WalletRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletRepository extends _i1.Mock implements _i4.WalletRepository {
  MockWalletRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Wallet> getWallet(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getWallet, [uid]),
            returnValue: _i5.Future<_i2.Wallet>.value(
              _FakeWallet_0(this, Invocation.method(#getWallet, [uid])),
            ),
          )
          as _i5.Future<_i2.Wallet>);

  @override
  _i5.Stream<_i2.Wallet> watchWallet(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#watchWallet, [uid]),
            returnValue: _i5.Stream<_i2.Wallet>.empty(),
          )
          as _i5.Stream<_i2.Wallet>);

  @override
  _i5.Future<_i3.WalletTransaction> executeTransaction({
    required String? uid,
    required int? amount,
    required String? direction,
    required _i6.WalletTransactionType? type,
    required String? idempotencyKey,
    String? referenceId,
    Map<String, dynamic>? metadata = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(#executeTransaction, [], {
              #uid: uid,
              #amount: amount,
              #direction: direction,
              #type: type,
              #idempotencyKey: idempotencyKey,
              #referenceId: referenceId,
              #metadata: metadata,
            }),
            returnValue: _i5.Future<_i3.WalletTransaction>.value(
              _FakeWalletTransaction_1(
                this,
                Invocation.method(#executeTransaction, [], {
                  #uid: uid,
                  #amount: amount,
                  #direction: direction,
                  #type: type,
                  #idempotencyKey: idempotencyKey,
                  #referenceId: referenceId,
                  #metadata: metadata,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.WalletTransaction>);

  @override
  _i5.Future<List<_i3.WalletTransaction>> getTransactionHistory(
    String? uid, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionHistory, [uid], {#limit: limit}),
            returnValue: _i5.Future<List<_i3.WalletTransaction>>.value(
              <_i3.WalletTransaction>[],
            ),
          )
          as _i5.Future<List<_i3.WalletTransaction>>);
}
