// Mocks generated by Mockito 5.4.6 from annotations
// in soteria/test/core/firebase/configuration_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:firebase_remote_config/firebase_remote_config.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:soteria/core/firebase/services/firebase_interfaces.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFirebaseRemoteConfig_0 extends _i1.SmartFake
    implements _i2.FirebaseRemoteConfig {
  _FakeFirebaseRemoteConfig_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IRemoteConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIRemoteConfigService extends _i1.Mock
    implements _i3.IRemoteConfigService {
  MockIRemoteConfigService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseRemoteConfig get instance =>
      (super.noSuchMethod(
            Invocation.getter(#instance),
            returnValue: _FakeFirebaseRemoteConfig_0(
              this,
              Invocation.getter(#instance),
            ),
          )
          as _i2.FirebaseRemoteConfig);

  @override
  _i4.Future<void> fetchAndActivate() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAndActivate, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setDefaults(Map<String, dynamic>? defaults) =>
      (super.noSuchMethod(
            Invocation.method(#setDefaults, [defaults]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  String getString(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getString, [key]),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#getString, [key]),
            ),
          )
          as String);

  @override
  bool getBool(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getBool, [key]),
            returnValue: false,
          )
          as bool);

  @override
  int getInt(String? key) =>
      (super.noSuchMethod(Invocation.method(#getInt, [key]), returnValue: 0)
          as int);

  @override
  double getDouble(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getDouble, [key]),
            returnValue: 0.0,
          )
          as double);
}
