// Mocks generated by Mockito 5.4.6 from annotations
// in soteria/test/features/notifications/notification_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:firebase_messaging/firebase_messaging.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:soteria/core/firebase/services/firebase_interfaces.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFirebaseMessaging_0 extends _i1.SmartFake
    implements _i2.FirebaseMessaging {
  _FakeFirebaseMessaging_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IMessagingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIMessagingService extends _i1.Mock implements _i3.IMessagingService {
  MockIMessagingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseMessaging get instance =>
      (super.noSuchMethod(
            Invocation.getter(#instance),
            returnValue: _FakeFirebaseMessaging_0(
              this,
              Invocation.getter(#instance),
            ),
          )
          as _i2.FirebaseMessaging);

  @override
  _i4.Stream<_i2.RemoteMessage> get onMessage =>
      (super.noSuchMethod(
            Invocation.getter(#onMessage),
            returnValue: _i4.Stream<_i2.RemoteMessage>.empty(),
          )
          as _i4.Stream<_i2.RemoteMessage>);

  @override
  _i4.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);
}
