// Mocks generated by Mockito 5.4.6 from annotations
// in soteria/test/features/question_content/taxonomy_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:soteria/features/question_content/domain/entities/category.dart'
    as _i4;
import 'package:soteria/features/question_content/domain/entities/subcategory.dart'
    as _i5;
import 'package:soteria/features/question_content/domain/entities/topic.dart'
    as _i6;
import 'package:soteria/features/question_content/domain/repositories/category_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i2.CategoryRepository {
  MockCategoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Category>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i3.Future<List<_i4.Category>>.value(<_i4.Category>[]),
          )
          as _i3.Future<List<_i4.Category>>);

  @override
  _i3.Stream<List<_i4.Category>> watchCategories() =>
      (super.noSuchMethod(
            Invocation.method(#watchCategories, []),
            returnValue: _i3.Stream<List<_i4.Category>>.empty(),
          )
          as _i3.Stream<List<_i4.Category>>);

  @override
  _i3.Future<_i4.Category?> getCategoryById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCategoryById, [id]),
            returnValue: _i3.Future<_i4.Category?>.value(),
          )
          as _i3.Future<_i4.Category?>);

  @override
  _i3.Future<List<_i5.Subcategory>> getSubcategories(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#getSubcategories, [categoryId]),
            returnValue: _i3.Future<List<_i5.Subcategory>>.value(
              <_i5.Subcategory>[],
            ),
          )
          as _i3.Future<List<_i5.Subcategory>>);

  @override
  _i3.Stream<List<_i5.Subcategory>> watchSubcategories(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#watchSubcategories, [categoryId]),
            returnValue: _i3.Stream<List<_i5.Subcategory>>.empty(),
          )
          as _i3.Stream<List<_i5.Subcategory>>);

  @override
  _i3.Future<_i5.Subcategory?> getSubcategoryById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSubcategoryById, [id]),
            returnValue: _i3.Future<_i5.Subcategory?>.value(),
          )
          as _i3.Future<_i5.Subcategory?>);

  @override
  _i3.Future<List<_i6.Topic>> getTopics(String? subcategoryId) =>
      (super.noSuchMethod(
            Invocation.method(#getTopics, [subcategoryId]),
            returnValue: _i3.Future<List<_i6.Topic>>.value(<_i6.Topic>[]),
          )
          as _i3.Future<List<_i6.Topic>>);

  @override
  _i3.Stream<List<_i6.Topic>> watchTopics(String? subcategoryId) =>
      (super.noSuchMethod(
            Invocation.method(#watchTopics, [subcategoryId]),
            returnValue: _i3.Stream<List<_i6.Topic>>.empty(),
          )
          as _i3.Stream<List<_i6.Topic>>);

  @override
  _i3.Future<_i6.Topic?> getTopicById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTopicById, [id]),
            returnValue: _i3.Future<_i6.Topic?>.value(),
          )
          as _i3.Future<_i6.Topic?>);

  @override
  _i3.Future<void> seedDefaultCategories() =>
      (super.noSuchMethod(
            Invocation.method(#seedDefaultCategories, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
