import '../models/milestone.dart';
import '../models/season_reward_definition.dart';

class MilestoneRegistry {
  static const List<MilestoneDefinition> definitions = [
    MilestoneDefinition(
      id: 'welcome_bonus',
      name: 'Welcome Gift',
      description: 'Start your journey with a bonus!',
      type: MilestoneType.welcome,
      category: MilestoneCategory.participation,
      threshold: 1,
      icon: 'stars_rounded',
      rewardType: RewardType.coins,
      rewardAmount: 50,
      displayOrder: -1,
    ),
    MilestoneDefinition(
      id: 'first_game',
      name: 'First Step',
      description: 'Complete your first competitive game.',
      type: MilestoneType.count,
      category: MilestoneCategory.participation,
      threshold: 1,
      icon: 'stars_rounded',
      rewardType: RewardType.coins,
      rewardAmount: 50,
      displayOrder: 0,
    ),
    MilestoneDefinition(
      id: 'first_win',
      name: 'First Blood',
      description: 'Win your first competitive game.',
      type: MilestoneType.win,
      category: MilestoneCategory.victory,
      threshold: 1,
      icon: 'emoji_events_rounded',
      rewardType: RewardType.coins,
      rewardAmount: 100,
      displayOrder: 1,
    ),
    MilestoneDefinition(
      id: 'streak_5',
      name: 'Hot Streak',
      description: 'Achieve a 5-win streak.',
      type: MilestoneType.streak,
      category: MilestoneCategory.victory,
      threshold: 5,
      icon: 'local_fire_department_rounded',
      rewardType: RewardType.coins,
      rewardAmount: 250,
      displayOrder: 2,
    ),

    MilestoneDefinition(
      id: 'wins_10',
      name: 'Decathlon',
      description: 'Win 10 competitive games.',
      type: MilestoneType.win,
      category: MilestoneCategory.victory,
      threshold: 10,
      icon: 'military_tech_rounded',
      rewardType: RewardType.coins,
      rewardAmount: 500,
      displayOrder: 4,
    ),
    MilestoneDefinition(
      id: 'level_10',
      name: 'Rising Star',
      description: 'Reach Level 10.',
      type: MilestoneType.count, // Using count for level here as proxy
      category: MilestoneCategory.general,
      threshold: 10,
      icon: 'auto_awesome_rounded',
      rewardType: RewardType.xp,
      rewardAmount: 1000,
      displayOrder: 5,
    ),
    MilestoneDefinition(
      id: 'matches_25',
      name: 'Veteran',
      description: 'Complete 25 competitive matches.',
      type: MilestoneType.count,
      category: MilestoneCategory.participation,
      threshold: 25,
      icon: 'shield_rounded',
      rewardType: RewardType.coins,
      rewardAmount: 1000,
      displayOrder: 6,
    ),
    MilestoneDefinition(
      id: 'wins_50',
      name: 'Half Century',
      description: 'Win 50 competitive games.',
      type: MilestoneType.win,
      category: MilestoneCategory.victory,
      threshold: 50,
      icon: 'workspace_premium_rounded',
      rewardType: RewardType.coins,
      rewardAmount: 2500,
      displayOrder: 7,
    ),
    MilestoneDefinition(
      id: 'rank_gold',
      name: 'Golden Standard',
      description: 'Reach Gold tier.',
      type: MilestoneType.rank,
      category: MilestoneCategory.ranking,
      threshold: 1,
      icon: 'military_tech_rounded',
      rewardType: RewardType.coins,
      rewardAmount: 1000,
      displayOrder: 8,
    ),
    MilestoneDefinition(
      id: 'rank_platinum',
      name: 'Platinum Soul',
      description: 'Reach Platinum tier.',
      type: MilestoneType.rank,
      category: MilestoneCategory.ranking,
      threshold: 1,
      icon: 'verified_user_rounded',
      rewardType: RewardType.coins,
      rewardAmount: 2000,
      displayOrder: 9,
    ),
    MilestoneDefinition(
      id: 'rank_diamond',
      name: 'Diamond Heart',
      description: 'Reach Diamond tier.',
      type: MilestoneType.rank,
      category: MilestoneCategory.ranking,
      threshold: 1,
      icon: 'diamond_rounded',
      rewardType: RewardType.coins,
      rewardAmount: 5000,
      displayOrder: 10,
    ),
    MilestoneDefinition(
      id: 'top_100',
      name: 'Global Elite',
      description: 'Finish a season in the top 100.',
      type: MilestoneType.position,
      category: MilestoneCategory.ranking,
      threshold: 100,
      icon: 'public_rounded',
      rewardType: RewardType.coins,
      rewardAmount: 10000,
      displayOrder: 11,
    ),
  ];

  static MilestoneDefinition? getById(String id) {
    for (final def in definitions) {
      if (def.id == id) return def;
    }
    return null;
  }
}
