// Mocks generated by Mockito 5.4.6 from annotations
// in soteria/test/features/question_content/data/repositories/question_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:soteria/features/question_content/data/data_sources/firestore_data_source.dart'
    as _i2;
import 'package:soteria/features/question_content/data/models/question_dto.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FirestoreQuestionDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreQuestionDataSource extends _i1.Mock
    implements _i2.FirestoreQuestionDataSource {
  @override
  _i3.Future<List<_i4.QuestionDto>> fetchQuestions({
    String? categoryId,
    String? subcategoryId,
    String? topicId,
    String? difficulty,
    String? status,
    int? limit = 10,
    String? startAfterId,
    List<String>? tags,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchQuestions, [], {
              #categoryId: categoryId,
              #subcategoryId: subcategoryId,
              #topicId: topicId,
              #difficulty: difficulty,
              #status: status,
              #limit: limit,
              #startAfterId: startAfterId,
              #tags: tags,
            }),
            returnValue: _i3.Future<List<_i4.QuestionDto>>.value(
              <_i4.QuestionDto>[],
            ),
            returnValueForMissingStub: _i3.Future<List<_i4.QuestionDto>>.value(
              <_i4.QuestionDto>[],
            ),
          )
          as _i3.Future<List<_i4.QuestionDto>>);

  @override
  _i3.Future<_i4.QuestionDto?> fetchQuestionById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchQuestionById, [id]),
            returnValue: _i3.Future<_i4.QuestionDto?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.QuestionDto?>.value(),
          )
          as _i3.Future<_i4.QuestionDto?>);

  @override
  _i3.Stream<_i4.QuestionDto?> watchQuestion(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchQuestion, [id]),
            returnValue: _i3.Stream<_i4.QuestionDto?>.empty(),
            returnValueForMissingStub: _i3.Stream<_i4.QuestionDto?>.empty(),
          )
          as _i3.Stream<_i4.QuestionDto?>);

  @override
  _i3.Future<void> saveQuestion(_i4.QuestionDto? question) =>
      (super.noSuchMethod(
            Invocation.method(#saveQuestion, [question]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveQuestionsBatch(List<_i4.QuestionDto>? questions) =>
      (super.noSuchMethod(
            Invocation.method(#saveQuestionsBatch, [questions]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
