// Mocks generated by Mockito 5.4.6 from annotations
// in soteria/test/features/question_content/domain/selection/question_selection_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:soteria/features/question_content/domain/entities/difficulty.dart'
    as _i5;
import 'package:soteria/features/question_content/domain/entities/question.dart'
    as _i4;
import 'package:soteria/features/question_content/domain/repositories/question_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [QuestionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuestionRepository extends _i1.Mock
    implements _i2.QuestionRepository {
  MockQuestionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Question>> getQuestions({
    String? categoryId,
    String? subcategoryId,
    String? topicId,
    _i5.Difficulty? difficulty,
    int? limit = 10,
    String? startAfterId,
    List<String>? tags,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestions, [], {
              #categoryId: categoryId,
              #subcategoryId: subcategoryId,
              #topicId: topicId,
              #difficulty: difficulty,
              #limit: limit,
              #startAfterId: startAfterId,
              #tags: tags,
            }),
            returnValue: _i3.Future<List<_i4.Question>>.value(<_i4.Question>[]),
          )
          as _i3.Future<List<_i4.Question>>);

  @override
  _i3.Future<_i4.Question?> getQuestionById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestionById, [id]),
            returnValue: _i3.Future<_i4.Question?>.value(),
          )
          as _i3.Future<_i4.Question?>);

  @override
  _i3.Stream<_i4.Question?> watchQuestion(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#watchQuestion, [id]),
            returnValue: _i3.Stream<_i4.Question?>.empty(),
          )
          as _i3.Stream<_i4.Question?>);

  @override
  _i3.Future<void> syncQuestionsPool({
    String? categoryId,
    _i5.Difficulty? difficulty,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncQuestionsPool, [], {
              #categoryId: categoryId,
              #difficulty: difficulty,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Question>> getQuestionsByStatus(
    _i4.QuestionStatus? status, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestionsByStatus, [status], {#limit: limit}),
            returnValue: _i3.Future<List<_i4.Question>>.value(<_i4.Question>[]),
          )
          as _i3.Future<List<_i4.Question>>);
}
