// Mocks generated by Mockito 5.4.6 from annotations
// in soteria/test/features/auth/logout_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:soteria/core/identity/models/user_game_profile.dart' as _i8;
import 'package:soteria/core/identity/models/user_identity.dart' as _i6;
import 'package:soteria/core/identity/models/user_profile.dart' as _i7;
import 'package:soteria/core/identity/models/user_session.dart' as _i5;
import 'package:soteria/core/identity/repositories/identity_repository.dart'
    as _i4;
import 'package:soteria/features/auth/domain/use_cases/logout_use_case.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i2.LogoutUseCase {
  MockLogoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [IdentityRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIdentityRepository extends _i1.Mock
    implements _i4.IdentityRepository {
  MockIdentityRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i5.UserSession?> get sessionChanges =>
      (super.noSuchMethod(
            Invocation.getter(#sessionChanges),
            returnValue: _i3.Stream<_i5.UserSession?>.empty(),
          )
          as _i3.Stream<_i5.UserSession?>);

  @override
  _i3.Future<_i5.UserSession?> getActiveSession() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveSession, []),
            returnValue: _i3.Future<_i5.UserSession?>.value(),
          )
          as _i3.Future<_i5.UserSession?>);

  @override
  _i3.Future<_i6.UserIdentity?> getUserIdentity(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserIdentity, [uid]),
            returnValue: _i3.Future<_i6.UserIdentity?>.value(),
          )
          as _i3.Future<_i6.UserIdentity?>);

  @override
  _i3.Future<_i7.UserProfile?> getUserProfile(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, [uid]),
            returnValue: _i3.Future<_i7.UserProfile?>.value(),
          )
          as _i3.Future<_i7.UserProfile?>);

  @override
  _i3.Future<_i8.UserGameProfile?> getUserGameProfile(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserGameProfile, [uid]),
            returnValue: _i3.Future<_i8.UserGameProfile?>.value(),
          )
          as _i3.Future<_i8.UserGameProfile?>);

  @override
  _i3.Future<void> saveSession(_i5.UserSession? session) =>
      (super.noSuchMethod(
            Invocation.method(#saveSession, [session]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearSession() =>
      (super.noSuchMethod(
            Invocation.method(#clearSession, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateUserProfile(String? uid, _i7.UserProfile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [uid, profile]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateUserGameProfile(
    String? uid,
    _i8.UserGameProfile? profile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserGameProfile, [uid, profile]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> uploadProfilePicture(String? uid, String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfilePicture, [uid, filePath]),
            returnValue: _i3.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#uploadProfilePicture, [uid, filePath]),
              ),
            ),
          )
          as _i3.Future<String>);
}
