// Mocks generated by Mockito 5.4.6 from annotations
// in soteria/test/features/analytics/practice_analytics_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:soteria/features/analytics/domain/models/question_analytics.dart'
    as _i6;
import 'package:soteria/features/analytics/domain/repositories/question_analytics_repository.dart'
    as _i3;
import 'package:soteria/features/auth/domain/repositories/auth_repository.dart'
    as _i9;
import 'package:soteria/features/auth/models/authentication_result.dart' as _i2;
import 'package:soteria/features/practice/domain/models/practice_result.dart'
    as _i8;
import 'package:soteria/features/practice/domain/repositories/practice_result_repository.dart'
    as _i7;
import 'package:soteria/features/quiz/domain/models/question_result.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthenticationResult_0 extends _i1.SmartFake
    implements _i2.AuthenticationResult {
  _FakeAuthenticationResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [QuestionAnalyticsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuestionAnalyticsRepository extends _i1.Mock
    implements _i3.QuestionAnalyticsRepository {
  MockQuestionAnalyticsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> recordEvent(
    String? sessionId,
    String? userId,
    _i5.QuestionResult? result,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#recordEvent, [sessionId, userId, result]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> recordEvents(
    String? sessionId,
    String? userId,
    List<_i5.QuestionResult>? results,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#recordEvents, [sessionId, userId, results]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Set<String>> getRecentlyAnsweredIds(
    String? userId, {
    Duration? within,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getRecentlyAnsweredIds,
              [userId],
              {#within: within},
            ),
            returnValue: _i4.Future<Set<String>>.value(<String>{}),
          )
          as _i4.Future<Set<String>>);

  @override
  _i4.Future<_i6.QuestionAnalytics?> getQuestionAnalytics(
    String? questionId,
    String? version,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestionAnalytics, [questionId, version]),
            returnValue: _i4.Future<_i6.QuestionAnalytics?>.value(),
          )
          as _i4.Future<_i6.QuestionAnalytics?>);

  @override
  _i4.Future<List<_i6.QuestionAnalytics>> getQuestionVersionHistory(
    String? questionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getQuestionVersionHistory, [questionId]),
            returnValue: _i4.Future<List<_i6.QuestionAnalytics>>.value(
              <_i6.QuestionAnalytics>[],
            ),
          )
          as _i4.Future<List<_i6.QuestionAnalytics>>);

  @override
  _i4.Future<List<_i6.QuestionAnalytics>> getReviewSignals({
    double? lowAccuracyThreshold = 0.3,
    double? highAccuracyThreshold = 0.95,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getReviewSignals, [], {
              #lowAccuracyThreshold: lowAccuracyThreshold,
              #highAccuracyThreshold: highAccuracyThreshold,
            }),
            returnValue: _i4.Future<List<_i6.QuestionAnalytics>>.value(
              <_i6.QuestionAnalytics>[],
            ),
          )
          as _i4.Future<List<_i6.QuestionAnalytics>>);

  @override
  _i4.Future<void> updateMetrics(_i5.QuestionResult? result) =>
      (super.noSuchMethod(
            Invocation.method(#updateMetrics, [result]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [PracticeResultRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPracticeResultRepository extends _i1.Mock
    implements _i7.PracticeResultRepository {
  MockPracticeResultRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> recordResult(
    _i8.PracticeResult? result, {
    bool? rewardsEligible = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #recordResult,
              [result],
              {#rewardsEligible: rewardsEligible},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i8.PracticeResult>> getRecentResults(
    String? userId, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentResults, [userId], {#limit: limit}),
            returnValue: _i4.Future<List<_i8.PracticeResult>>.value(
              <_i8.PracticeResult>[],
            ),
          )
          as _i4.Future<List<_i8.PracticeResult>>);

  @override
  _i4.Future<List<_i8.PracticeResult>> getResults(
    String? userId, {
    int? limit = 20,
    _i8.PracticeResult? lastResult,
    String? categoryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getResults,
              [userId],
              {#limit: limit, #lastResult: lastResult, #categoryId: categoryId},
            ),
            returnValue: _i4.Future<List<_i8.PracticeResult>>.value(
              <_i8.PracticeResult>[],
            ),
          )
          as _i4.Future<List<_i8.PracticeResult>>);

  @override
  _i4.Future<List<_i8.PracticeResult>> getResultsByDateRange(
    String? userId,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getResultsByDateRange, [userId, start, end]),
            returnValue: _i4.Future<List<_i8.PracticeResult>>.value(
              <_i8.PracticeResult>[],
            ),
          )
          as _i4.Future<List<_i8.PracticeResult>>);

  @override
  _i4.Future<void> deleteResult(String? userId, String? resultId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteResult, [userId, resultId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i9.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<String?> get userIdChanges =>
      (super.noSuchMethod(
            Invocation.getter(#userIdChanges),
            returnValue: _i4.Stream<String?>.empty(),
          )
          as _i4.Stream<String?>);

  @override
  _i4.Future<_i2.AuthenticationResult> signInWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmail, [email, password]),
            returnValue: _i4.Future<_i2.AuthenticationResult>.value(
              _FakeAuthenticationResult_0(
                this,
                Invocation.method(#signInWithEmail, [email, password]),
              ),
            ),
          )
          as _i4.Future<_i2.AuthenticationResult>);

  @override
  _i4.Future<_i2.AuthenticationResult> signUpWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmail, [email, password]),
            returnValue: _i4.Future<_i2.AuthenticationResult>.value(
              _FakeAuthenticationResult_0(
                this,
                Invocation.method(#signUpWithEmail, [email, password]),
              ),
            ),
          )
          as _i4.Future<_i2.AuthenticationResult>);

  @override
  _i4.Future<_i2.AuthenticationResult> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i4.Future<_i2.AuthenticationResult>.value(
              _FakeAuthenticationResult_0(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
          )
          as _i4.Future<_i2.AuthenticationResult>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> sendEmailVerification() =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isEmailVerified() =>
      (super.noSuchMethod(
            Invocation.method(#isEmailVerified, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
