// Mocks generated by Mockito 5.4.6 from annotations
// in soteria/test/features/player/competitive_history_isolation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:soteria/features/player/domain/models/season_result.dart'
    as _i4;
import 'package:soteria/features/player/domain/repositories/competitive_history_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CompetitiveHistoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompetitiveHistoryRepository extends _i1.Mock
    implements _i2.CompetitiveHistoryRepository {
  @override
  _i3.Future<List<_i4.SeasonResult>> getSeasonResults(
    String? userId, {
    int? limit = 20,
    dynamic startAfter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getSeasonResults,
              [userId],
              {#limit: limit, #startAfter: startAfter},
            ),
            returnValue: _i3.Future<List<_i4.SeasonResult>>.value(
              <_i4.SeasonResult>[],
            ),
            returnValueForMissingStub: _i3.Future<List<_i4.SeasonResult>>.value(
              <_i4.SeasonResult>[],
            ),
          )
          as _i3.Future<List<_i4.SeasonResult>>);

  @override
  _i3.Future<_i4.SeasonResult?> getSeasonResult(
    String? userId,
    String? seasonId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSeasonResult, [userId, seasonId]),
            returnValue: _i3.Future<_i4.SeasonResult?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.SeasonResult?>.value(),
          )
          as _i3.Future<_i4.SeasonResult?>);

  @override
  _i3.Future<_i4.SeasonResult?> getLatestSeasonResult(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestSeasonResult, [userId]),
            returnValue: _i3.Future<_i4.SeasonResult?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.SeasonResult?>.value(),
          )
          as _i3.Future<_i4.SeasonResult?>);

  @override
  _i3.Future<_i4.SeasonResult?> getBestSeasonResult(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getBestSeasonResult, [userId]),
            returnValue: _i3.Future<_i4.SeasonResult?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.SeasonResult?>.value(),
          )
          as _i3.Future<_i4.SeasonResult?>);

  @override
  _i3.Stream<List<_i4.SeasonResult>> watchSeasonHistory(
    String? userId, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchSeasonHistory, [userId], {#limit: limit}),
            returnValue: _i3.Stream<List<_i4.SeasonResult>>.empty(),
            returnValueForMissingStub:
                _i3.Stream<List<_i4.SeasonResult>>.empty(),
          )
          as _i3.Stream<List<_i4.SeasonResult>>);
}
