// Mocks generated by Mockito 5.4.6 from annotations
// in soteria/test/features/player/match_history_domain_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:soteria/features/player/domain/models/competitive_result.dart'
    as _i4;
import 'package:soteria/features/player/domain/models/rank_change.dart' as _i6;
import 'package:soteria/features/player/domain/repositories/competitive_result_repository.dart'
    as _i2;
import 'package:soteria/features/player/domain/repositories/rank_history_repository.dart'
    as _i5;
import 'package:soteria/features/quiz/domain/models/quiz_enums.dart' as _i9;
import 'package:soteria/features/quiz/domain/models/quiz_result.dart' as _i8;
import 'package:soteria/features/quiz/domain/repositories/quiz_history_repository.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CompetitiveResultRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompetitiveResultRepository extends _i1.Mock
    implements _i2.CompetitiveResultRepository {
  MockCompetitiveResultRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> recordResult(_i4.CompetitiveResult? result) =>
      (super.noSuchMethod(
            Invocation.method(#recordResult, [result]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.CompetitiveResult>> getRecentResults(
    String? userId, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentResults, [userId], {#limit: limit}),
            returnValue: _i3.Future<List<_i4.CompetitiveResult>>.value(
              <_i4.CompetitiveResult>[],
            ),
          )
          as _i3.Future<List<_i4.CompetitiveResult>>);

  @override
  _i3.Future<List<_i4.CompetitiveResult>> getResults(
    String? userId, {
    int? limit = 20,
    _i4.CompetitiveResult? lastResult,
    String? seasonId,
    String? mode,
    _i4.CompetitiveOutcome? outcome,
    String? opponentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getResults,
              [userId],
              {
                #limit: limit,
                #lastResult: lastResult,
                #seasonId: seasonId,
                #mode: mode,
                #outcome: outcome,
                #opponentId: opponentId,
              },
            ),
            returnValue: _i3.Future<List<_i4.CompetitiveResult>>.value(
              <_i4.CompetitiveResult>[],
            ),
          )
          as _i3.Future<List<_i4.CompetitiveResult>>);

  @override
  _i3.Stream<List<_i4.CompetitiveResult>> watchRecentResults(
    String? userId, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchRecentResults, [userId], {#limit: limit}),
            returnValue: _i3.Stream<List<_i4.CompetitiveResult>>.empty(),
          )
          as _i3.Stream<List<_i4.CompetitiveResult>>);
}

/// A class which mocks [RankHistoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRankHistoryRepository extends _i1.Mock
    implements _i5.RankHistoryRepository {
  MockRankHistoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addRankChange(_i6.RankChange? change) =>
      (super.noSuchMethod(
            Invocation.method(#addRankChange, [change]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> acknowledgeRankChange(String? changeId) =>
      (super.noSuchMethod(
            Invocation.method(#acknowledgeRankChange, [changeId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i6.RankChange>> watchRankHistory(
    String? userId, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchRankHistory, [userId], {#limit: limit}),
            returnValue: _i3.Stream<List<_i6.RankChange>>.empty(),
          )
          as _i3.Stream<List<_i6.RankChange>>);

  @override
  _i3.Future<List<_i6.RankChange>> getRankHistory(
    String? userId, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRankHistory, [userId], {#limit: limit}),
            returnValue: _i3.Future<List<_i6.RankChange>>.value(
              <_i6.RankChange>[],
            ),
          )
          as _i3.Future<List<_i6.RankChange>>);

  @override
  _i3.Future<List<_i6.RankChange>> getRecentPromotions(
    String? userId, {
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentPromotions, [userId], {#limit: limit}),
            returnValue: _i3.Future<List<_i6.RankChange>>.value(
              <_i6.RankChange>[],
            ),
          )
          as _i3.Future<List<_i6.RankChange>>);

  @override
  _i3.Future<List<_i6.RankChange>> getUnacknowledgedChanges(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUnacknowledgedChanges, [userId]),
            returnValue: _i3.Future<List<_i6.RankChange>>.value(
              <_i6.RankChange>[],
            ),
          )
          as _i3.Future<List<_i6.RankChange>>);

  @override
  _i3.Stream<List<_i6.RankChange>> watchUnacknowledgedChanges(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchUnacknowledgedChanges, [userId]),
            returnValue: _i3.Stream<List<_i6.RankChange>>.empty(),
          )
          as _i3.Stream<List<_i6.RankChange>>);
}

/// A class which mocks [QuizHistoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockQuizHistoryRepository extends _i1.Mock
    implements _i7.QuizHistoryRepository {
  MockQuizHistoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addResult(_i8.QuizResult? result) =>
      (super.noSuchMethod(
            Invocation.method(#addResult, [result]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i8.QuizResult?> getResult(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#getResult, [sessionId]),
            returnValue: _i3.Future<_i8.QuizResult?>.value(),
          )
          as _i3.Future<_i8.QuizResult?>);

  @override
  _i3.Future<List<_i8.QuizResult>> getResults(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#getResults, [playerId]),
            returnValue: _i3.Future<List<_i8.QuizResult>>.value(
              <_i8.QuizResult>[],
            ),
          )
          as _i3.Future<List<_i8.QuizResult>>);

  @override
  _i3.Future<List<_i8.QuizResult>> getRecentResults(
    String? playerId, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentResults, [playerId], {#limit: limit}),
            returnValue: _i3.Future<List<_i8.QuizResult>>.value(
              <_i8.QuizResult>[],
            ),
          )
          as _i3.Future<List<_i8.QuizResult>>);

  @override
  _i3.Future<List<_i8.QuizResult>> getResultsByMode(
    String? playerId,
    _i9.GameMode? mode,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getResultsByMode, [playerId, mode]),
            returnValue: _i3.Future<List<_i8.QuizResult>>.value(
              <_i8.QuizResult>[],
            ),
          )
          as _i3.Future<List<_i8.QuizResult>>);

  @override
  _i3.Future<List<_i8.QuizResult>> getResultsByCategory(
    String? playerId,
    String? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getResultsByCategory, [playerId, category]),
            returnValue: _i3.Future<List<_i8.QuizResult>>.value(
              <_i8.QuizResult>[],
            ),
          )
          as _i3.Future<List<_i8.QuizResult>>);

  @override
  _i3.Future<List<_i8.QuizResult>> getResultsByDifficulty(
    String? playerId,
    _i9.Difficulty? difficulty,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getResultsByDifficulty, [playerId, difficulty]),
            returnValue: _i3.Future<List<_i8.QuizResult>>.value(
              <_i8.QuizResult>[],
            ),
          )
          as _i3.Future<List<_i8.QuizResult>>);

  @override
  _i3.Future<List<_i8.QuizResult>> getResultsByDateRange(
    String? playerId,
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getResultsByDateRange, [playerId, start, end]),
            returnValue: _i3.Future<List<_i8.QuizResult>>.value(
              <_i8.QuizResult>[],
            ),
          )
          as _i3.Future<List<_i8.QuizResult>>);

  @override
  _i3.Future<List<_i8.QuizResult>> getBestResults(
    String? playerId, {
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBestResults, [playerId], {#limit: limit}),
            returnValue: _i3.Future<List<_i8.QuizResult>>.value(
              <_i8.QuizResult>[],
            ),
          )
          as _i3.Future<List<_i8.QuizResult>>);

  @override
  _i3.Future<_i8.QuizResult?> getLatestResult(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestResult, [playerId]),
            returnValue: _i3.Future<_i8.QuizResult?>.value(),
          )
          as _i3.Future<_i8.QuizResult?>);

  @override
  _i3.Future<int> getTotalCompleted(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalCompleted, [playerId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> deleteResult(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteResult, [sessionId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearHistory(String? playerId) =>
      (super.noSuchMethod(
            Invocation.method(#clearHistory, [playerId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
